title: Hyounjun (HJ) Chang | Portfolio
email: hyounjun.chang@colorado.edu
description: "Looking for FPGA/Verification Roles or in Related Fields"

url: "https://hyounjunchang.github.io"
baseurl: ""
author: Hyounjun (HJ) Chang

collections:
  projects:
    output: true
    permalink: /projects/:path/

defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: article

theme: minima

plugins:
  - jekyll-feed